# site settings
title: Richter Science Communication
subtitle: Interactive exhibits • workshops • science engagement
email: robertricht@gmail.com
description: >
  Science communication through interactive installations, workshops and maker-education.<br />
  Based in Berlin — projects with festivals, museums and educational partners.
baseurl: "" # user site -> empty
url: "https://robertricht.github.io/Richter-Sci-Comm/" # <-- DEINUSERNAME ersetzen
author: Dr. Robert Richter

street_address: Oranienburger Str. 39
city: Berlin
state:
zip_code: 10117
country: Germany
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# Icons are not shown if value is empty
socials:
  GitHub:
  GitLab:
  Instagram:
  LinkedIn:
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
